name: test
on: push

jobs:
  build:
    name: Execute Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Execute
        run: mvn test
      
