name: test
on: push

jobs:
  build:
    name: Execute Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0
      - name: Config JRE
        uses: actions/setup-java@v1
        with:
          java-version: '9.0.4'
          java-package: jdk
      - name: Execute
        run: mvn test
      
